# -*- coding: utf-8 -*-
"""funções_cursos-prouni

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ym_4R6bkvNWeiHz6awOhnTsNTHSeIyX
"""

import pandas as pd

"""// abrindo arquivo do tipo xlsx"""

df_prouni = pd.read_excel('/content/cursos-prouni.csv.xlsx')

df_prouni

"""// aumentando a quantidade de linha visualisadas"""



pd.set_option('display.max_rows',1000)

df_prouni['curso_busca'].value_counts()

df_prouni['mensalidade'].mode()

"""//.agg serve para agrupar"""



df_prouni.groupby(['uf_busca','curso_busca'])['mensalidade'].agg(['median'])



"""// .sort_values serve para ordenar"""

df_prouni.groupby(['uf_busca','curso_busca'])['mensalidade'].agg(['median']).sort_values(['uf_busca','median'])

"""// criando uma função"""

def duplica_bolsa(rows):
  nova_bolsa = rows*2
  return nova_bolsa

"""// criando um data frame"""

df = df_prouni[['uf_busca', 'curso_busca','mensalidade','bolsa_integral_ampla']]
df

"""//.apply() chama a função"""

df['nova_bolsa'] = df['bolsa_integral_ampla'].apply(duplica_bolsa)

df

df['nova_bolsa'] = df['nova_bolsa'].fillna(2)

df

df_prouni

"""//função lambda = simplifica funções para apenas uma linha de código"""

df['nova_bolsa_lambda'] = df['bolsa_integral_ampla'].apply(lambda x: x * 2)

df

df  = df.assign(nv_bolsa_lambda2 = lambda x : (x['bolsa_integral_ampla'] * 2))

fruta[0:]